### ISSUE TITLE
Allow specifying tailwind.config.js location

### ISSUE THREAD

**Issue by teddybradford** [kingdaro/typescript-plugin-tw-template#3]
The `twin.macro` package recommends keeping `tailwind.config.js` in the `src` directory of a project:

```js
// package.json
"babelMacros": {
  "twin": {
    // Place tailwind.config.js in the src folder so
    // it can be imported into your theme provider
    "config": "src/tailwind.config.js"
  }
},
```
(via https://github.com/ben-rogerson/twin.macro#create-react-app--emotion)

Is it possible to configure this Tailwind plugin to use a custom `tailwind.config.js` location?

**Comment by teddybradford** [comment]
On second thought, maybe this plugin should just defer to the `babelMacros.twin.config` value?

**Comment by itsMapleLeaf** [comment]
[This is one of the unchecked items on the TODO, currently.](https://github.com/kingdaro/typescript-plugin-tw-template#todo) I didn't implement it myself because I didn't have a need for it, but PRs are welcome 🙂 



> On second thought, maybe this plugin should just defer to the `babelMacros.twin.config` value?

Though it's not stated explicitly, this project is meant to be library agnostic, as to work with twin.macro, or any other library that has the same API (like tailwind.macro). So I'm hesitant to read specifically from twin's config

---

For the record, you can also import/resolve the config through [preval.macro](https://github.com/kentcdodds/preval.macro). As a bonus, this lets you exclude tailwind's helpers from the bundle, and any parts of the config which you don't need. Example:

```ts
import preval from "preval.macro"

const screens = preval`
  const resolveConfig = require('tailwindcss/resolveConfig')
  const config = resolveConfig(require('../../tailwind.config'))
  module.exports = config.theme.screens
`

export const screenQueries = {
  small: `(max-width: ${screens.md})`,
  medium: `(min-width: ${screens.md}) and (max-width: ${screens.lg})`,
  large: `(min-width: ${screens.lg})`,
}
```

**Comment by A-Shleifman** [comment]
Another **workaround** would be to create a `tailwind.config.js` in the root and import the actual config from `/src`:

```js
// tailwind.config.js

module.exports = require('./src/tailwind.config');
```
